service: ais2geojson

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: ${opt:namespace}-serverless-deployments-${self:provider.stage}-${self:provider.region}
    blockPublicAccess: true
    serverSideEncryption: AES256

functions:
  ais2geojson:
    handler: handler.ais2geoson
    layers:
      - {Ref: Ais2geojsonDashlayerLambdaLayer}

layers:
  ais2geojson-layer:
    path: layer
    description: Make the ais2geojson command line parser available to functions.
    compatibleRuntimes:
      - java11
      - nodejs12.x
      - python3.8
      - dotnetcore2.1
      - go1.x
    licenseInfo: MIT
    allowedAccounts:
      - '*'
