service: maponit-ais2geojson

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: ${opt:namespace}-serverless-deployments-${self:provider.stage}-${self:provider.region}
    blockPublicAccess: true
    serverSideEncryption: AES256

functions:
  ais2geojson:
    handler: handler.ais2geojson
    layers:
      - {Ref: Ais2geojsonLambdaLayer}

layers:
  ais2geojson:
    path: layer
    description: Make the ais2geojson command line parser available to functions.
    licenseInfo: MIT
    allowedAccounts:
      - '*'
